Feature/add editing actions support
elegion/ios-TableViewDataProvider pull request #4
Opened 2020-01-16 11:24 UTC by chebur

2020-02-05 11:10 UTC, ildar-gilfanov approved these changes

2020-04-03 08:19 UTC, galandezzz requested changes

2020-04-03 08:19 UTC, galandezzz commented on Example/Example/ViewController.swift
> +        }, trailingSwipeActionsConfiguration: { _ in
Нарушены гайдлайны тут и на строке ниже. Параметры в кложурах переносятся на новую строку

2020-04-03 08:24 UTC, chebur commented on Example/Example/ViewController.swift
> +        }, trailingSwipeActionsConfiguration: { _ in
надо для этого прикрутить в проект линтер

предлагаю это сделать в рамках отдельной задачи

2020-04-03 09:34 UTC, merged